# -*- coding: utf-8 -*-
"""devoirs PEF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xznQ9fXVU4r5Q5JI5Wiwi8OLPwUTTOFp
"""

import streamlit as st
import pandas as pd
import joblib

# Charger le pipeline sauvegardé
mlp_pipeline = joblib.load('mlp_fevfvc_pipeline.pkl')

# Charger les données d'entraînement pour l'IC
url = "https://raw.githubusercontent.com/pefura/IFPERA/main/Cameroon_lung_function.csv"
df = pd.read_csv(url, sep=';')
dataset = df[df['sex'] == 2][['age', 'height', 'fev', 'fvc']].copy()
dataset['fevfvc'] = dataset['fev'] / dataset['fvc']
X_train = dataset[['age', 'height']]
y_train = dataset['fevfvc']

st.title("Prédiction du rapport fev/fvc chez la femme camerounaise (MLP)")

age = st.number_input("Âge (années)", min_value=4, max_value=90, value=30)
height = st.number_input("Taille (cm)", min_value=100, max_value=200, value=160)

if st.button("Prédire"):
    pred, lower, upper = predict_fevfvc_with_interval(age, height, mlp_pipeline, X_train, y_train)
    st.write(f"Valeur prédite (espérance) : {pred:.3f}")
    st.write(f"Intervalle de confiance à 90% : [{lower:.3f} ; {upper:.3f}]"