# -*- coding: utf-8 -*-
"""lien devoir .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138PVm4G_RUfSBf-Yj1zeYYU4GeSslYQW
"""

pip install streamlit
import streamlit as st
import pandas as pd

st.title("Prédiction du rapport fev/fvc chez la femme camerounaise")
age = st.number_input("Âge (années)", min_value=4, max_value=90, value=30)
height = st.number_input("Taille (cm)", min_value=100, max_value=200, value=160)

if st.button("Prédire"):
    mean, lower, upper = predict_fevfvc_with_interval(age, height)
    st.write(f"Valeur prédite (espérance) : {mean:.3f}")
    st.write(f"Intervalle de confiance à 90% : [{lower:.3f} ; {upper:.3f}]")